language: haskell
ghc:
  - 8.0
  - 7.8
  - 7.6
install:
  - cabal install happy alex
  - cabal install --only-dependencies --enable-tests --enable-benchmarks
script:
  - cabal configure --enable-tests --enable-benchmarks && cabal build && cabal test && cabal bench
